// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0h04K5fxFqG3KgzYgRIsAPmVuwxSJFlM',
    appId: '1:942361532654:web:3bfa9020cb8e6c170a7bff',
    messagingSenderId: '942361532654',
    projectId: 'my-portfolio-df88f',
    authDomain: 'my-portfolio-df88f.firebaseapp.com',
    storageBucket: 'my-portfolio-df88f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiCEw_swW91eLXk_ok_v2BCUHZh1oft8',
    appId: '1:942361532654:android:a1e1127d398f05de0a7bff',
    messagingSenderId: '942361532654',
    projectId: 'my-portfolio-df88f',
    storageBucket: 'my-portfolio-df88f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8mA5eU69xfjXFlloQTyykqzispkYVwdA',
    appId: '1:942361532654:ios:b507590e48fc64720a7bff',
    messagingSenderId: '942361532654',
    projectId: 'my-portfolio-df88f',
    storageBucket: 'my-portfolio-df88f.firebasestorage.app',
    iosBundleId: 'com.example.mourytech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8mA5eU69xfjXFlloQTyykqzispkYVwdA',
    appId: '1:942361532654:ios:b507590e48fc64720a7bff',
    messagingSenderId: '942361532654',
    projectId: 'my-portfolio-df88f',
    storageBucket: 'my-portfolio-df88f.firebasestorage.app',
    iosBundleId: 'com.example.mourytech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0h04K5fxFqG3KgzYgRIsAPmVuwxSJFlM',
    appId: '1:942361532654:web:11f00e1c56cf6e7a0a7bff',
    messagingSenderId: '942361532654',
    projectId: 'my-portfolio-df88f',
    authDomain: 'my-portfolio-df88f.firebaseapp.com',
    storageBucket: 'my-portfolio-df88f.firebasestorage.app',
  );

}